### ISSUE TITLE
translate issue

### ISSUE THREAD

**Issue by tosone** [97-things/97-things-every-programmer-should-know#12]
I'm Chinese. Could i translate this book into chinese？ I like this book very much.

Email:tosone@qq.com

**Comment by Semigradsky** [comment]
Of course! Glad to hear it.

**Comment by bigplants** [comment]
@Semigradsky 
Hi,
I'm Japanese. This is a great book for all engineers.
And I want many Japanese engineers to read the book.
Could I translate this book into Japanese right?

**Comment by Semigradsky** [comment]
Have fun!

**Comment by namiko** [comment]
Hi,
I'm german and just started to create a german translation.
Hoping that's fine for you.

**Comment by Semigradsky** [comment]
@namiko maybe [this utils](https://github.com/97-things/ns-utils) will help you
