### ISSUE TITLE
Use <ol> instead of <ul>

### ISSUE THREAD

**Issue by aTei** [97-things/97-things-every-programmer-should-know#17]
As it named "97 things" sounds right to use ordered list with 1., 2., 3... instead of bullets

**Comment by Semigradsky** [comment]
Where?

**Comment by aTei** [comment]
Summary page https://github.com/97-things/97-things-every-programmer-should-know/blob/master/en/SUMMARY.md

**Comment by Semigradsky** [comment]
PR is welcome ;)

**Comment by aTei** [comment]
<3
