### ISSUE TITLE
Turkish version

### ISSUE THREAD

**Issue by barankaya** [97-things/97-things-every-programmer-should-know#38]
Hi @Semigradsky.

I will start the translation to Turkish.

What do you think?

Thanks

**Comment by Semigradsky** [comment]
Feel free to send PR! =)

**Comment by barankaya** [comment]
Thanks :)

**Comment by yusufalp** [comment]
@barankaya Can I also join you?

**Comment by barankaya** [comment]
@yusufalp Of course you can join. I forked the project, I tried to translate 51 of them into Turkish. I opened a pull request, I send each page as I finish it. If you want, we can continue by taking the project in my account and adding it, or if you have another suggestion, we can do it too.

**Comment by barankaya** [comment]
Hi @Semigradsky, can you check PR :)

**Comment by Semigradsky** [comment]
LGTM 👍

**Comment by barankaya** [comment]
Thank you @Semigradsky, 
Will I be seen as contribute or is there something else I need to do?
