### ISSUE TITLE
Please re-release gitbook

### ISSUE THREAD

**Issue by vegerot** [97-things/97-things-every-programmer-should-know#46]
I see that https://github.com/97-things/97-things-every-programmer-should-know/commit/4616033ffc59c303cdb7dc62ef3cfe6786d7cb21 was merged nearly two years ago but the typo is still present on https://97-things-every-x-should-know.gitbooks.io/97-things-every-programmer-should-know/content/en/thing_13/

Please re-release the gitbook with the patches made since the last release 🙂

**Comment by Semigradsky** [comment]
Thank you! New link: https://97-things-every-x-should-know.gitbook.io/97-things-every-programmer-should-know/en/thing_13
I can't re-release on old link.
