### ISSUE TITLE
for contribute

### ISSUE THREAD

**Issue by barankaya** [97-things/97-things-every-programmer-should-know#50]
Thank you @Semigradsky, 
Will I be seen as contribute or is there something else I need to do?

_Originally posted by @barankaya in https://github.com/97-things/97-things-every-programmer-should-know/issues/38#issuecomment-1170818464_

**Comment by Semigradsky** [comment]
Hi! Do you mean this section - https://github.com/97-things/97-things-every-programmer-should-know/graphs/contributors ?
Or mention on https://github.com/97-things/97-things-every-programmer-should-know/blob/master/LANGS.md for example?

**Comment by barankaya** [comment]
i meant to say that -> https://github.com/97-things/97-things-every-programmer-should-know/graphs/contributors

**Comment by Semigradsky** [comment]
```
commit 9934f6ca38070009d8ffd55227c45ec5e3cf9d86
Author: baran kaya <barankaya@barans-MacBook-Air.local>
Date:   Tue Jun 28 18:52:50 2022 +0300

    added thing_97
```
You used `barankaya@barans-MacBook-Air.local` email instead of `0barankaya@gmail.com` from your github account.
That is why are you not showing up as contributor (I think that is a reason). I will try to change email on commits on the weekend.

**Comment by barankaya** [comment]
I understand. I created new pull request for right email account. Can you check it?

https://github.com/barankaya/97-things-every-programmer-should-know/pull/1

**Comment by Semigradsky** [comment]
Yes, now you in a list 👍 I will change early commits on the weekend.

**Comment by Semigradsky** [comment]
Done!
